name = "eletroled-blog"
compatibility_date = "2026-06-17"
workers_dev = false

routes = [
  { pattern = "blog.consertoeletroled.com/*", zone_name = "consertoeletroled.com" }
]

[assets]
directory = "../../dist"
not_found_handling = "404-page"
html_handling = "auto-trailing-slash"
