name = "eletroled-blog-www-redirect"
main = "src/index.js"
compatibility_date = "2026-06-16"
workers_dev = false

routes = [
  { pattern = "www.blog.consertoeletroled.com/*", zone_name = "consertoeletroled.com" }
]
