name = "eletroled-main-site-llms"
main = "src/index.js"
compatibility_date = "2026-06-16"
workers_dev = false

routes = [
  { pattern = "consertoeletroled.com/*", zone_name = "consertoeletroled.com" }
]
